# Generated by Django 3.0.3 on 2020-02-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.AutoField(primary_key=True, serialize=False)),
                ('tweet_name', models.CharField(max_length=25)),
                ('tweet_body', models.CharField(max_length=50)),
                ('tweet_crated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
